### ISSUE TITLE
Looking at a model generated (v 1.0.x), I can't see how to navigate via imports

### ISSUE THREAD

**Issue by fuhrmanator** [fuhrmanator/FamixTypeScriptImporter#19]
In TypeScript, it would be useful to see relationships among imports. I though in Java, this was done through `outgoingReferences` at the class level. In TypeScript, this should probably be at the Module level?

**Comment by NicolasAnquetil** [comment]
first
- Reference is often misunderstood (because of the name). In Famix it specifically means "something (a method) referring to a Type (a class)" e.g.: `o instsanceof AClass` is a reference to "AClass"
- There is a `FamixTImport` association that relates `TWithImports` to `TImportable`. It seems like what you need no ?
-A `TSModule` would be both `TWithImports` to `TImportable` and then you create also a `TSImport` that uses  `FamixTImport`. And that's it, `TSModule` will have relations: `importingEntity` and `importedEntity`

This is how it is done in Java:
![image](https://github.com/fuhrmanator/FamixTypeScriptImporter/assets/14889146/145fd55f-e263-4a63-ac28-8384a993a93c)

What do you think ?

**Comment by fuhrmanator** [comment]
Fixed in #24
