### ISSUE TITLE
FamixTypeScriptComments don't use source anchors, but store data in content

### ISSUE THREAD

**Issue by fuhrmanator** [fuhrmanator/FamixTypeScriptImporter#29]
In 1.1.x, comments show up differently than in FamixJavaComment.

They appear in `content` rather than pointing to the source code as in sourceAnchor (FamixJava).

![image](https://github.com/fuhrmanator/FamixTypeScriptImporter/assets/7606540/b9561bf2-93b0-41a1-9700-070b9c72c92e)

The down side of this is that the `\r\n` (line breaks) don't appear to parse properly in Moose. 

![image](https://github.com/fuhrmanator/FamixTypeScriptImporter/assets/7606540/1eb87c37-60f3-44cd-9be2-dc3426f91d5d)

Moose seems to pick up the `content` property for the **Source Text** tab, so I'm not sure what's supposed to happen. We can just model comments as in FamixJava (sourceAnchor). @NicolasAnquetil?

**Comment by NicolasAnquetil** [comment]
Doing it like Java is usually a good idea
(Because Java is the most extensively used meta-model, including in industrial context)

The difference is in the subclass/trait of SourceAnchor used:
- `FamixTHasImmediateSource` stores the comment in the source anchor, no need to have access to the source code once the model is built
- `FamixTFileAnchor` and descendants point to a source file

After that, they both answer to `#sourceText` that returns the source (accessing the file for `FamixTFileAnchor`), and this is what the **Source Text** tab of the inspector uses
