### ISSUE TITLE
Many "Unknown property" messages appear in Pharo Transcript when loading TypeScript model

### ISSUE THREAD

**Issue by fuhrmanator** [fuhrmanator/FamixTypeScriptImporter#54]
![image](https://github.com/fuhrmanator/FamixTypeScriptImporter/assets/7606540/eab8ab3e-ee32-4dc2-bf8b-ef69064399b3)

**Comment by NicolasAnquetil** [comment]
can you provide a small model to test ?

**Comment by fuhrmanator** [comment]
This is Moose 10, using the MM at https://github.com/fuhrmanator/FamixTypeScript?tab=readme-ov-file#loading-from-a-playground

[simplemodel.typescript.json](https://github.com/fuhrmanator/FamixTypeScriptImporter/files/14782454/simplemodel.typescript.json)
[Transcript.txt](https://github.com/fuhrmanator/FamixTypeScriptImporter/files/14782455/Transcript.txt)

The source file is this TypeScript file (test_src/basicExport.ts)

```ts
        export const variable1 = "Hello, World!";
```

**Comment by NicolasAnquetil** [comment]
Note: main problem was actually with #start_line

Analysis: It is also derived (no setter, only a getter).
It is computed from the #startPos and the length of the lines in the source file.
To use #startLine: one should use the trait `FamixTFileNavigation` instead of `FamixTIndexedFileNavigation`.
The former wants startLine/startColumn/endLine/endColumn

If one wants #startLine from `FamixTIndexedFileNavigation`, it is derived (computed), providing one has access to the #completeText of the file, itself subject to having a correct #rootFolder.

**Comment by NicolasAnquetil** [comment]
If you agree with all this, you can close the issue.
Tx for helping

**Comment by fuhrmanator** [comment]
Thanks for your help! I agree with these but will leave it open until we make the changes to the MM and importer.

**Comment by fuhrmanator** [comment]
Many, not all, are fixed in #63. Remaining ones are problems with concretizations/genericity.
